name: Suggérer une fonctionnalité
description: Permet de suggérer une fonctionnalité sur un service de Quartzly !
body:
  - type: dropdown
    attributes:
      label: Service
      options:
        - Application Web
        - Application PC
        - Application Mobile
        - Site Vitrine
        - Documentation
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description de la fonctionnalité
      description: 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Captures d'écran et/ou vidéos
      description: Ajoutez des captures d'écran et/ou des vidéos illustrant la fonctionnalité.
      placeholder: Faites glisser et déposez les captures d'écran/vidéos dans cette boîte.
    validations:
      required: false
